
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALERTA BOOL BOOL BOOL DESLIGAR DIFERENTE DISPOSITIVO ENTAO ENVIAR E_LOGICO GT IGUAL_IGUAL LIGAR LT MAIOR_IGUAL MENOR_IGUAL MSG NAMEDEVICE NUM PARA SE SENAO SET TODOSprogram : devices cmdsdevices : device devicesdevices : devicedevice : DISPOSITIVO ":" "{" NAMEDEVICE "}"device : DISPOSITIVO ":" "{" NAMEDEVICE "," NAMEDEVICE "}"cmds : cmd "." cmdscmds : cmd "."cmds : cmd : attrib\n| obsact\n| actattrib : SET NAMEDEVICE "=" varvar : NUM\n| BOOLobsact : SE obs ENTAO actobsact : SE obs ENTAO act SENAO actobs : NAMEDEVICE oplogic varobs : NAMEDEVICE oplogic var E_LOGICO obsoplogic : GT\n| LT\n| MAIOR_IGUAL\n| MENOR_IGUAL\n| IGUAL_IGUAL\n| DIFERENTEact : action NAMEDEVICEact : ENVIAR ALERTA "(" MSG ")" NAMEDEVICEact : ENVIAR ALERTA "(" MSG "," NAMEDEVICE ")" NAMEDEVICEact : ENVIAR ALERTA "(" MSG ")" PARA TODOS ":" dev_listdev_list : NAMEDEVICE "," dev_listdev_list : NAMEDEVICEaction : LIGAR\n| DESLIGAR'
    
_lr_action_items = {'DISPOSITIVO':([0,3,43,55,],[4,4,-4,-5,]),'$end':([1,2,3,5,16,18,25,43,55,],[0,-8,-3,-1,-2,-7,-6,-4,-5,]),'SET':([2,3,16,18,43,55,],[10,-3,-2,10,-4,-5,]),'SE':([2,3,16,18,43,55,],[11,-3,-2,11,-4,-5,]),'ENVIAR':([2,3,16,18,27,43,45,55,],[13,-3,-2,13,13,-4,13,-5,]),'LIGAR':([2,3,16,18,27,43,45,55,],[14,-3,-2,14,14,-4,14,-5,]),'DESLIGAR':([2,3,16,18,27,43,45,55,],[15,-3,-2,15,15,-4,15,-5,]),':':([4,56,],[17,58,]),'.':([6,7,8,9,22,37,38,39,40,50,52,59,60,61,63,],[18,-9,-10,-11,-25,-12,-13,-14,-15,-16,-26,-27,-28,-30,-29,]),'NAMEDEVICE':([10,11,12,14,15,24,44,46,47,48,57,58,62,],[19,21,22,-31,-32,36,49,21,52,54,59,61,61,]),'ALERTA':([13,],[23,]),'{':([17,],[24,]),'=':([19,],[26,]),'ENTAO':([20,38,39,41,51,],[27,-13,-14,-17,-18,]),'GT':([21,],[29,]),'LT':([21,],[30,]),'MAIOR_IGUAL':([21,],[31,]),'MENOR_IGUAL':([21,],[32,]),'IGUAL_IGUAL':([21,],[33,]),'DIFERENTE':([21,],[34,]),'SENAO':([22,40,52,59,60,61,63,],[-25,45,-26,-27,-28,-30,-29,]),'(':([23,],[35,]),'NUM':([26,28,29,30,31,32,33,34,],[38,38,-19,-20,-21,-22,-23,-24,]),'BOOL':([26,28,29,30,31,32,33,34,],[39,39,-19,-20,-21,-22,-23,-24,]),'MSG':([35,],[42,]),'}':([36,49,],[43,55,]),',':([36,42,61,],[44,48,62,]),'E_LOGICO':([38,39,41,],[-13,-14,46,]),')':([42,54,],[47,57,]),'PARA':([47,],[53,]),'TODOS':([53,],[56,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,16,]),'device':([0,3,],[3,3,]),'cmds':([2,18,],[5,25,]),'cmd':([2,18,],[6,6,]),'attrib':([2,18,],[7,7,]),'obsact':([2,18,],[8,8,]),'act':([2,18,27,45,],[9,9,40,50,]),'action':([2,18,27,45,],[12,12,12,12,]),'obs':([11,46,],[20,51,]),'oplogic':([21,],[28,]),'var':([26,28,],[37,41,]),'dev_list':([58,62,],[60,63,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','parser_c.py',34),
  ('devices -> device devices','devices',2,'p_devices_multiple','parser_c.py',38),
  ('devices -> device','devices',1,'p_devices_single','parser_c.py',42),
  ('device -> DISPOSITIVO : { NAMEDEVICE }','device',5,'p_device_simple','parser_c.py',46),
  ('device -> DISPOSITIVO : { NAMEDEVICE , NAMEDEVICE }','device',7,'p_device_observation','parser_c.py',51),
  ('cmds -> cmd . cmds','cmds',3,'p_cmds_multiple','parser_c.py',62),
  ('cmds -> cmd .','cmds',2,'p_cmds_single','parser_c.py',66),
  ('cmds -> <empty>','cmds',0,'p_cmds_empty','parser_c.py',70),
  ('cmd -> attrib','cmd',1,'p_cmd','parser_c.py',74),
  ('cmd -> obsact','cmd',1,'p_cmd','parser_c.py',75),
  ('cmd -> act','cmd',1,'p_cmd','parser_c.py',76),
  ('attrib -> SET NAMEDEVICE = var','attrib',4,'p_attrib','parser_c.py',81),
  ('var -> NUM','var',1,'p_var','parser_c.py',91),
  ('var -> BOOL','var',1,'p_var','parser_c.py',92),
  ('obsact -> SE obs ENTAO act','obsact',4,'p_obsact_if','parser_c.py',100),
  ('obsact -> SE obs ENTAO act SENAO act','obsact',6,'p_obsact_if_else','parser_c.py',105),
  ('obs -> NAMEDEVICE oplogic var','obs',3,'p_obs_single','parser_c.py',111),
  ('obs -> NAMEDEVICE oplogic var E_LOGICO obs','obs',5,'p_obs_multiple','parser_c.py',115),
  ('oplogic -> GT','oplogic',1,'p_oplogic','parser_c.py',119),
  ('oplogic -> LT','oplogic',1,'p_oplogic','parser_c.py',120),
  ('oplogic -> MAIOR_IGUAL','oplogic',1,'p_oplogic','parser_c.py',121),
  ('oplogic -> MENOR_IGUAL','oplogic',1,'p_oplogic','parser_c.py',122),
  ('oplogic -> IGUAL_IGUAL','oplogic',1,'p_oplogic','parser_c.py',123),
  ('oplogic -> DIFERENTE','oplogic',1,'p_oplogic','parser_c.py',124),
  ('act -> action NAMEDEVICE','act',2,'p_act_action','parser_c.py',129),
  ('act -> ENVIAR ALERTA ( MSG ) NAMEDEVICE','act',6,'p_act_alerta_msg','parser_c.py',133),
  ('act -> ENVIAR ALERTA ( MSG , NAMEDEVICE ) NAMEDEVICE','act',8,'p_act_alerta_obs','parser_c.py',137),
  ('act -> ENVIAR ALERTA ( MSG ) PARA TODOS : dev_list','act',9,'p_act_broadcast','parser_c.py',144),
  ('dev_list -> NAMEDEVICE , dev_list','dev_list',3,'p_dev_list_multiple','parser_c.py',152),
  ('dev_list -> NAMEDEVICE','dev_list',1,'p_dev_list_single','parser_c.py',156),
  ('action -> LIGAR','action',1,'p_action','parser_c.py',160),
  ('action -> DESLIGAR','action',1,'p_action','parser_c.py',161),
]
